### PR TITLE
Development

### PR DESCRIPTION
**Pull request by kelvin8773**
done with requested features.

### CODE REVIEW

**Review by inhaq — CHANGES_REQUESTED** [review]
Good job, just minor fix to `my_count` and you're done.
 - `my_count` should work with and without block e.g. `[1,2,3].my_count` should return `3`

Once updated, kindly resubmit for review.

**Comment by kelvin8773** [comment]
feature updated, please help review it again, thanks!

**Review by inhaq — APPROVED** [review]
It's 👍🏻
Before merging, kindly remove `test cases` from `enumerable.rb` file. You'll do proper testing in the next project.
Good luck with the next project.

**Comment by kelvin8773** [comment]
thanks for the review,  already remove the test case.

**Pull request merged**
